services:
  brics_bridge:
    build:
      context: .
      no_cache: true
    container_name: brics_bridge
    restart: unless-stopped
    user: "0"
    command:
      - '-stats=false'
      - '-kaspa=host.docker.internal:18110'
    ports:
      - 18220:18220
      - 2114:2114
    extra_hosts:
      - host.docker.internal:host-gateway
